CREATE TYPE [UDT].[DepartmentCode] FROM [NVARCHAR](10) NOT NULL
GO

CREATE TYPE [UDT].[DepartmentName] FROM [NVARCHAR](50) NOT NULL
GO

CREATE TYPE [UDT].[Enrollment] FROM [INT] NULL
GO

CREATE TYPE [UDT].[ClassSection] FROM [NVARCHAR](4) NULL
GO

CREATE TYPE [UDT].[ClassCode] FROM [NVARCHAR](5) NULL
GO

CREATE TYPE [UDT].[MaxEnrollment] FROM [INT] NULL
GO

CREATE TYPE [UDT].[CourseClassTime] FROM [NVARCHAR](20) NULL
GO

CREATE TYPE [UDT].[CourseClassDay] FROM [NVARCHAR](10) NULL
GO